name: Build Ngrok Image

# Manual trigger build
# curl -H "Accept: application/vnd.github.everest-preview+json" \
#     -H "Authorization: token ${GITHUB_TOKEN}" \
#     --request POST \
#     --data '{"event_type": "manual run"}' \
#     https://api.github.com/repos/jgreat/ngrok-k8s/dispatches

on:
  repository_dispatch: {}
  schedule:
    - cron: "0 14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Env
      env:
        NGROK_ARCHIVE_URL: "https://dl.equinox.io/ngrok/ngrok/stable/archive"
        NGROK_STABLE_URL: "https://dl.equinox.io/ngrok/ngrok/stable"
      run: |
        NGROK_VERSION=$(curl -sS ${NGROK_STABLE_URL} | grep Version | sed -r 's/.*>Version (.*)<.*/\1/')
        NGROK_URL=$(curl -sS ${NGROK_ARCHIVE_URL} | grep ngrok-${NGROK_VERSION}-linux-amd64.deb | sed -r 's/^.*href="(.*)" .*$/\1/')
        echo "NGROK_VERSION=${NGROK_VERSION}" >> $GITHUB_ENV
        echo "NGROK_URL=${NGROK_URL}" >> $GITHUB_ENV
    - name: Build and Publish Image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: jgreat/ngrok
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: NGROK_URL
        tags: ${{ env.NGROK_VERSION }},latest
